books/urls.py
from django.conf.urls import patterns, include, url
from book_search import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    #views
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.logreg ,name="logreg"),
    url(r'^login/', views.logreg ,name="logreg"),
    url(r'^results/', views.results, name="results"),
    url(r'^search/', views.search, name="search"),
    url(r'^home/', views.home, name="home"),
    url(r'^add_book_page/', views.add_book_page, name="add_book_page"),

    #functions
    url(r'^register/', views.register, name="register"),
    url(r'^loger/', views.loger, name="loger"),
    url(r'^logout/', views.log_out, name="log_out"),
    url(r'^add_book/', views.add_book, name="add_book"),
    url(r'^get_account/', views.get_account, name="get_account"),
    url(r'^autocomplete/', views.autocomplete, name="autocomplete"),
)

book_search/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    book_id = models.AutoField(primary_key=True, db_column="book_id")
    title = models.CharField(max_length=140)
    is_fiction = models.BooleanField()

    class Meta:
        ordering = ['-book_id']
    def __str__(self):
        return str(self.book_id)

class Author(models.Model):
    author_id = models.AutoField(primary_key=True, db_column="author_id")
    af_name = models.CharField(max_length=140)
    al_name = models.CharField(max_length=140)
    afull_name = models.CharField(max_length=140)
    pseudonym = models.CharField(max_length=140)
    class Meta:
        ordering = ['-author_id']
    def __str__(self):
        return str(self.author_id)

class BookAuthor(models.Model):
    book_id = models.ForeignKey(Book, db_column="book_id")
    author_id = models.ForeignKey(Author, db_column="author_id")
    class Meta:
        ordering = ['-author_id']
    def __str__(self):
        return str(self.book_id)+"-"+str(self.author_id)

class Edition(models.Model):
    book_id = models.ForeignKey(Book, db_column='book_id')
    isbn = models.CharField(max_length=14, primary_key=True)
    pub_date = models.DateField()
    publisher = models.CharField(max_length=140)
    language = models.CharField(max_length=140)
    class Meta:
        ordering = ['-isbn']
    def __str__(self):
        return str(self.isbn)

class BookGenre(models.Model):
    book_id = models.ForeignKey(Book, db_column='book_id')
    genre = models.CharField(max_length=140)
    class Meta:
        ordering = ['-genre']
    def __str__(self):
        return str(self.genre) + "-" + str(self.book_id)

class Editor(models.Model):
    isbn = models.ForeignKey(Edition, db_column='isbn', primary_key=True)
    editor_name = models.CharField(max_length=250)
    class Meta:
        ordering = ['-editor_name']
    def __str__(self):
        return str(self.el_name)

book_search/forms.py
from django.contrib.auth.models import User
from models	import Book, Author, BookGenre, Editor, Edition,  BookAuthor
from django import forms
class acc():
	def accounts(self):
		return User.objects.all()

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('email','username','password','first_name','last_name')

class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ('title','is_fiction')

class BookGForm(forms.ModelForm):
	class Meta :
		model = BookGenre

class EditorForm(forms.ModelForm):
	class Meta:
		model = Editor


class EditionForm(forms.ModelForm):
	pub_date = forms.DateField()
	class Meta:
		model = Edition


class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = ('af_name', 'al_name', 'pseudonym')

templates/add_book.html
{% extends 'base.html' %}

{% block css %}
#book_form{
	margin-top:70px;
}
{% endblock css %}

{% block headline %}
{% endblock headline %}




{% block content %}
<form id="book_form" method="post" action="/add_book/"
                enctype="multipart/form-data">

            {% csrf_token %}
            {{book_form.as_p}}
            <p>
            <lable for="id_editor_name">Editor Name: </lable>
            {{editor_form.editor_name}}
            </p>
            <p>
            <lable for="id_publisher">Publisher: </lable>
            {{edition_form.publisher}}
            </p>
            <p>
            <lable for="id_pub_date">Date Published: </lable>
            {{edition_form.pub_date}}
            </p>
            <p>
            <lable for="id_language">Langgaue: </lable>
            {{edition_form.language}}
            </p>
            <p>
            <lable for="id_isbn">ISBN: </lable>
            {{edition_form.isbn}}
            </p>
            {{edition.author_id}}
            {{author_form.as_p}}
            <lable for="id_genre">Genre: </lable>
            {{bookg_form.genre}}

<input type="submit" name="submit" value="submit" class="btn btn-default" />
</form>

{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    {% block js %}{% endblock js %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    <title>{% block title %}Wicked Booktown{% endblock title %}</title>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic|Special+Elite' rel='stylesheet' type='text/css'>
    <style>
    {% block css %}



    {% endblock css %}
    </style>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/themes/smoothness/jquery-ui.css" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
    <script src="http://jquery-json.googlecode.com/files/jquery.json-2.2.min.js"></script>
    <script src="http://jquery-websocket.googlecode.com/files/jquery.websocket-0.0.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <script type="text/javascript">

    </script>

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
           {% block nav %}
    {% for group in user.groups.all %}
    {% if group.name == 'subscribed'%}
      <li><a href="{%url 'home'%}">Home</a></li>
      <li><a href="{%url 'search'%}">Search</a></li>
     {% endif %}
    {% endfor %}
            

            {% if user.is_superuser %}
             <li><a href="{%url 'home'%}">Home</a></li>
             <li><a href="{%url 'search'%}">Search</a></li>
            <li><a href="{%url 'add_book_page'%}">Add Book</a></li>
            {% endif %}
            {% endblock nav %}
          </ul>
        </div>
      </div>
    </div>


  <div class="container">
  {% block headline %}
  {% endblock headline%}

 

      {% block content %}

      {% endblock content %}
 </div>
    <div id="footer" class="footer navbar-fixed-bottom">
      <div class="container">
        <a id="login" class="btn btn-primary pull-right" 
        href="{% url 'admin:index' %}">Admin</a>
        {% if user.is_authenticated %}
            <a id="login" class="btn btn-primary pull-right" 
            href="/logout/">Logout</a>
        {% endif %}

      </div>
    </div>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block css %}

{% endblock css %}


{% block headline %}
{% if user.is_authenticated %}
<div id='welcome'>
	<h1>Welcome, {{user}}</h1>
	<p>Use the navigation at the top right-hand corner of the screen to move around book town. <br>
	<img src= 'http://localhost/book-town.jpg' />
	</p>
</div>

{% else %}
<h1>Please register or sign in</h1>
{% endif %}
{% endblock headline %}




{% block content %}

{% endblock content %}

templates/logreg.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}

#user_form{
	margin-top:70px;
}
#login_form{
    margin-top:70px;
}

<link

{% endblock css %}

{% block headline %}
{% endblock headline %}

{% block content %}

<div class='login' id='login_form'> 
      <form id="login_form" method="post" action="/loger/">
           <h1>Login to Booktown</h1>
              {% csrf_token %}
              Username: <input type="text" name="username" value="" size="50" />
              <br />
              Password: <input type="password" name="password" value="" size="50" />
              <br />

              <input type="submit" value="submit" />
  		</form>

  <!-- Button trigger modal -->
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Not a member?
  </button>


  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Register</h4>
        </div>
        <div class="modal-body">

          <form id="user_form" method="post" action="/register/"
                  enctype="multipart/form-data">

              {% csrf_token %}

              {{user_form.as_p}}

  <input type="submit" name="submit" value="Register" class="btn btn-default" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

      



{% endblock content %}

templates/registered.html
{% extends 'base.html' %}


{% block css %}

h1 {
	margin-top:60px;
}

{% endblock css %}

{% block headline %}
{% endblock headline %}




{% block content %}

 <h1>Register with booktown</h1>

{% if registered %}
        <strong>thank you for registering!</strong>
        <a href="/login/">Return to the homepage.</a><br />
        {% else %}
        <strong>register here!</strong><br />
{% endif %}
        
{% endblock content %}

templates/results.html
{% extends 'base.html' %}

{% block css %}

ul {
	list-style-type: none;
}

.result_sec{
	border:black 1pt solid;
	margin:20px;
	padding:10px;
	border-radius:10pt;
}

.failed_search{
  width: 600px;
  display: block;
  margin-left: auto;
  margin-right: auto;
}
#result{
	margin-top:60px;
}

{% endblock css %}

{% block headline %}
<div id="result" >

{% if result %}

<div id="margining">
<h1>Search Results for</h1>

{% if genre %}
<h2>Genre: {{genre}}</h2>
{% endif %}

{% if term %}
<h2>{{term}}: {{search}}</h2>
{% endif %}

{% if lucky %}
<h2>Feeling Lucky!</h2>
{% endif %}

{% for i in result %}
<div class="result_sec">
	<ul>
		<li><b>Title: </b> {{i.title}}</li>
		<li><b>Author: </b> {{i.author}}</li>
		<li><b>Genre: </b>{{i.genre}}
		<li><b>Pseudonym: </b> {{i.pseudonym}}</li>
		<li><b>Language: </b> {{i.language}}</li>
		<li><b>Date: </b> {{i.date}}</li>
		<li><b>Publisher: </b> {{i.publisher}}</li>
		<li><b>Editor :</b> {{i.editor}}</li>
		<li><b>ISBN: </b> {{i.isbn}}</li>
	</ul>
</div>

{% endfor %}
</div>
{% else %}

<div class="failed_search">
	<h1>Aww, I'm sorry your search sucks!</h1>
	<img src="http://10.0.112.1/404.png" />
</div>

{% endif %}
</div>
{% endblock headline %}


{% block content %}
{% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}

#search{
	margin-top:60px;
}

{% endblock css %}

{% block headline %}

{% if user.is_authenticated %}
<div class="container" id="search">
	<div id="greeting">
	<img src="{% static 'images/book.png' %}" alt="book" height='175'/>

		<h1>Greetings!<br></h1><h2> Welcome to the wicked book search engine
		</h2><br>
		<h3>
		Please enter your search terms and we will return some wicked books
		</h3> 
	</div>

</div>
	<div class="search_divs" name="various">

		<form class="search_form" name="input" action="/results/" method="get">
		<input type="hidden" name="type_is" value="1">

			<div class="ui-widget" style="margin-top:2em; font-family: 'Open Sans Condensed', sans-serif">
			<label for="tit">Title: </label>
			<input id="tit">
		
			<label for="auth">Author: </label>
			<input id="auth">
			
			<label for="pub">Publisher: </label>
			<input id="pub">
			</div>

		<div class="ui-widget" style="margin-top:2em; font-family: 'Special Elite', cursive;">
		Result:
		<div id="log" style="height: 200px; width: 300px; overflow: auto;" class="ui-widget-content"></div>
</div>
	</div>

	<div class="search_divs" id="genre">
		<form class="search_form" name="genresearch" action="/results/" method="get">	
		<input type="hidden" name="type_is" value="2">
		<legend>Search by genre</legend>
			<select class="btn btn-primary" tabindex="4" name="genre">
				{% for i in genrelist %}
					<option>{{i.genre}}</option>
				{% endfor %}
				
			</select>
			<input tabindex="5" type="submit" class="btn btn-primary"><br>
		</form>			
	</div>

	<div  id="lucky">
		<form class="search_form" name="luckysearch" action="/results/" method="get">	
		<input type="hidden" name="type_is" value="3">
		<legend>Feelin lucky? </legend>
			<input type="submit" value="Get random book" name="lucky" class="btn btn-primary">
		</form> 
	</div>


{% else %}
<h1>You are not signed in, dont have an account ? </h1>
<a href="/login/">Click here!</a>
{% endif %}

{% endblock headline %}




{% block content %}
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

<script>


$(function() {
	function log( message ) {
		$( "<div>" ).text( message ).prependTo( "#log" );
		$( "#log" ).scrollTop( 0 );
	}
	$( "#tit" ).autocomplete({
	source: "/autocomplete/",
	minLength: 2,

	select: function( event, ui ) {
	log( ui.item ?
	"Selected: " + ui.item.value + " aka " + ui.item.id :
	"Nothing selected, input was " + this.value );
	}
});




</script>
</head>






{% endblock content %}

templates/template.html
{% extends 'base.html' %}

{% block css %}{% endblock css %}

{% block headline %}
{% endblock headline %}




{% block content %}
{% endblock content %}